/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package el.stylian.sulawesi.commons

class LibraryUtils {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
